/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTravelsIndexRouteImport } from './routes/_authenticated/travels/index'
import { Route as AuthenticatedTravelsNewRouteImport } from './routes/_authenticated/travels/new'
import { Route as AuthenticatedTravelsTravelIdRouteRouteImport } from './routes/_authenticated/travels/$travelId/route'
import { Route as AuthenticatedTravelsTravelIdIndexRouteImport } from './routes/_authenticated/travels/$travelId/index'
import { Route as AuthenticatedTravelsTravelIdSummaryRouteImport } from './routes/_authenticated/travels/$travelId/summary'
import { Route as AuthenticatedTravelsTravelIdMembersRouteImport } from './routes/_authenticated/travels/$travelId/members'
import { Route as AuthenticatedTravelsTravelIdExpensesRouteImport } from './routes/_authenticated/travels/$travelId/expenses'
import { Route as AuthenticatedTravelsTravelIdEditRouteImport } from './routes/_authenticated/travels/$travelId/edit'
import { Route as AuthenticatedTravelsTravelIdCategoriesRouteImport } from './routes/_authenticated/travels/$travelId/categories'
import { Route as AuthenticatedTravelsTravelIdBudgetRouteImport } from './routes/_authenticated/travels/$travelId/budget'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsIndexRoute =
  AuthenticatedTravelsIndexRouteImport.update({
    id: '/travels/',
    path: '/travels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsNewRoute = AuthenticatedTravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsTravelIdRouteRoute =
  AuthenticatedTravelsTravelIdRouteRouteImport.update({
    id: '/travels/$travelId',
    path: '/travels/$travelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdIndexRoute =
  AuthenticatedTravelsTravelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdSummaryRoute =
  AuthenticatedTravelsTravelIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdMembersRoute =
  AuthenticatedTravelsTravelIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdExpensesRoute =
  AuthenticatedTravelsTravelIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdEditRoute =
  AuthenticatedTravelsTravelIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesRoute =
  AuthenticatedTravelsTravelIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdBudgetRoute =
  AuthenticatedTravelsTravelIdBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels/': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId/budget': typeof AuthenticatedTravelsTravelIdBudgetRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/travels/$travelId/members': typeof AuthenticatedTravelsTravelIdMembersRoute
  '/travels/$travelId/summary': typeof AuthenticatedTravelsTravelIdSummaryRoute
  '/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId/budget': typeof AuthenticatedTravelsTravelIdBudgetRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/travels/$travelId/members': typeof AuthenticatedTravelsTravelIdMembersRoute
  '/travels/$travelId/summary': typeof AuthenticatedTravelsTravelIdSummaryRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  '/_authenticated/travels/new': typeof AuthenticatedTravelsNewRoute
  '/_authenticated/travels/': typeof AuthenticatedTravelsIndexRoute
  '/_authenticated/travels/$travelId/budget': typeof AuthenticatedTravelsTravelIdBudgetRoute
  '/_authenticated/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/_authenticated/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/_authenticated/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/_authenticated/travels/$travelId/members': typeof AuthenticatedTravelsTravelIdMembersRoute
  '/_authenticated/travels/$travelId/summary': typeof AuthenticatedTravelsTravelIdSummaryRoute
  '/_authenticated/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/auth/verify'
    | '/travels/$travelId'
    | '/travels/new'
    | '/travels/'
    | '/travels/$travelId/budget'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/edit'
    | '/travels/$travelId/expenses'
    | '/travels/$travelId/members'
    | '/travels/$travelId/summary'
    | '/travels/$travelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/auth/verify'
    | '/travels/new'
    | '/travels'
    | '/travels/$travelId/budget'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/edit'
    | '/travels/$travelId/expenses'
    | '/travels/$travelId/members'
    | '/travels/$travelId/summary'
    | '/travels/$travelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/profile'
    | '/auth/verify'
    | '/_authenticated/travels/$travelId'
    | '/_authenticated/travels/new'
    | '/_authenticated/travels/'
    | '/_authenticated/travels/$travelId/budget'
    | '/_authenticated/travels/$travelId/categories'
    | '/_authenticated/travels/$travelId/edit'
    | '/_authenticated/travels/$travelId/expenses'
    | '/_authenticated/travels/$travelId/members'
    | '/_authenticated/travels/$travelId/summary'
    | '/_authenticated/travels/$travelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/': {
      id: '/_authenticated/travels/'
      path: '/travels'
      fullPath: '/travels/'
      preLoaderRoute: typeof AuthenticatedTravelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/new': {
      id: '/_authenticated/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof AuthenticatedTravelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId': {
      id: '/_authenticated/travels/$travelId'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId/': {
      id: '/_authenticated/travels/$travelId/'
      path: '/'
      fullPath: '/travels/$travelId/'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/summary': {
      id: '/_authenticated/travels/$travelId/summary'
      path: '/summary'
      fullPath: '/travels/$travelId/summary'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdSummaryRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/members': {
      id: '/_authenticated/travels/$travelId/members'
      path: '/members'
      fullPath: '/travels/$travelId/members'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdMembersRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/expenses': {
      id: '/_authenticated/travels/$travelId/expenses'
      path: '/expenses'
      fullPath: '/travels/$travelId/expenses'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdExpensesRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/edit': {
      id: '/_authenticated/travels/$travelId/edit'
      path: '/edit'
      fullPath: '/travels/$travelId/edit'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdEditRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/categories': {
      id: '/_authenticated/travels/$travelId/categories'
      path: '/categories'
      fullPath: '/travels/$travelId/categories'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/budget': {
      id: '/_authenticated/travels/$travelId/budget'
      path: '/budget'
      fullPath: '/travels/$travelId/budget'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdBudgetRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
  }
}

interface AuthenticatedTravelsTravelIdRouteRouteChildren {
  AuthenticatedTravelsTravelIdBudgetRoute: typeof AuthenticatedTravelsTravelIdBudgetRoute
  AuthenticatedTravelsTravelIdCategoriesRoute: typeof AuthenticatedTravelsTravelIdCategoriesRoute
  AuthenticatedTravelsTravelIdEditRoute: typeof AuthenticatedTravelsTravelIdEditRoute
  AuthenticatedTravelsTravelIdExpensesRoute: typeof AuthenticatedTravelsTravelIdExpensesRoute
  AuthenticatedTravelsTravelIdMembersRoute: typeof AuthenticatedTravelsTravelIdMembersRoute
  AuthenticatedTravelsTravelIdSummaryRoute: typeof AuthenticatedTravelsTravelIdSummaryRoute
  AuthenticatedTravelsTravelIdIndexRoute: typeof AuthenticatedTravelsTravelIdIndexRoute
}

const AuthenticatedTravelsTravelIdRouteRouteChildren: AuthenticatedTravelsTravelIdRouteRouteChildren =
  {
    AuthenticatedTravelsTravelIdBudgetRoute:
      AuthenticatedTravelsTravelIdBudgetRoute,
    AuthenticatedTravelsTravelIdCategoriesRoute:
      AuthenticatedTravelsTravelIdCategoriesRoute,
    AuthenticatedTravelsTravelIdEditRoute:
      AuthenticatedTravelsTravelIdEditRoute,
    AuthenticatedTravelsTravelIdExpensesRoute:
      AuthenticatedTravelsTravelIdExpensesRoute,
    AuthenticatedTravelsTravelIdMembersRoute:
      AuthenticatedTravelsTravelIdMembersRoute,
    AuthenticatedTravelsTravelIdSummaryRoute:
      AuthenticatedTravelsTravelIdSummaryRoute,
    AuthenticatedTravelsTravelIdIndexRoute:
      AuthenticatedTravelsTravelIdIndexRoute,
  }

const AuthenticatedTravelsTravelIdRouteRouteWithChildren =
  AuthenticatedTravelsTravelIdRouteRoute._addFileChildren(
    AuthenticatedTravelsTravelIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTravelsTravelIdRouteRoute: typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  AuthenticatedTravelsNewRoute: typeof AuthenticatedTravelsNewRoute
  AuthenticatedTravelsIndexRoute: typeof AuthenticatedTravelsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTravelsTravelIdRouteRoute:
    AuthenticatedTravelsTravelIdRouteRouteWithChildren,
  AuthenticatedTravelsNewRoute: AuthenticatedTravelsNewRoute,
  AuthenticatedTravelsIndexRoute: AuthenticatedTravelsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
