/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthenticatedTravelsIndexRouteImport } from './routes/_authenticated/travels/index'
import { Route as AuthenticatedTravelsNewRouteImport } from './routes/_authenticated/travels/new'
import { Route as AuthenticatedTravelsTravelIdRouteRouteImport } from './routes/_authenticated/travels/$travelId/route'
import { Route as AuthenticatedTravelsTravelIdIndexRouteImport } from './routes/_authenticated/travels/$travelId/index'
import { Route as AuthenticatedTravelsTravelIdExpensesRouteImport } from './routes/_authenticated/travels/$travelId/expenses'
import { Route as AuthenticatedTravelsTravelIdEditRouteImport } from './routes/_authenticated/travels/$travelId/edit'
import { Route as AuthenticatedTravelsTravelIdCategoriesRouteImport } from './routes/_authenticated/travels/$travelId/categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTravelsIndexRoute =
  AuthenticatedTravelsIndexRouteImport.update({
    id: '/travels/',
    path: '/travels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsNewRoute = AuthenticatedTravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsTravelIdRouteRoute =
  AuthenticatedTravelsTravelIdRouteRouteImport.update({
    id: '/travels/$travelId',
    path: '/travels/$travelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdIndexRoute =
  AuthenticatedTravelsTravelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdExpensesRoute =
  AuthenticatedTravelsTravelIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdEditRoute =
  AuthenticatedTravelsTravelIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesRoute =
  AuthenticatedTravelsTravelIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedTravelsTravelIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels/': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  '/_authenticated/travels/new': typeof AuthenticatedTravelsNewRoute
  '/_authenticated/travels/': typeof AuthenticatedTravelsIndexRoute
  '/_authenticated/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesRoute
  '/_authenticated/travels/$travelId/edit': typeof AuthenticatedTravelsTravelIdEditRoute
  '/_authenticated/travels/$travelId/expenses': typeof AuthenticatedTravelsTravelIdExpensesRoute
  '/_authenticated/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/travels/$travelId'
    | '/travels/new'
    | '/travels/'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/edit'
    | '/travels/$travelId/expenses'
    | '/travels/$travelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/travels/new'
    | '/travels'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/edit'
    | '/travels/$travelId/expenses'
    | '/travels/$travelId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/auth/verify'
    | '/_authenticated/travels/$travelId'
    | '/_authenticated/travels/new'
    | '/_authenticated/travels/'
    | '/_authenticated/travels/$travelId/categories'
    | '/_authenticated/travels/$travelId/edit'
    | '/_authenticated/travels/$travelId/expenses'
    | '/_authenticated/travels/$travelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/travels/': {
      id: '/_authenticated/travels/'
      path: '/travels'
      fullPath: '/travels/'
      preLoaderRoute: typeof AuthenticatedTravelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/new': {
      id: '/_authenticated/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof AuthenticatedTravelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId': {
      id: '/_authenticated/travels/$travelId'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId/': {
      id: '/_authenticated/travels/$travelId/'
      path: '/'
      fullPath: '/travels/$travelId/'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/expenses': {
      id: '/_authenticated/travels/$travelId/expenses'
      path: '/expenses'
      fullPath: '/travels/$travelId/expenses'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdExpensesRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/edit': {
      id: '/_authenticated/travels/$travelId/edit'
      path: '/edit'
      fullPath: '/travels/$travelId/edit'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdEditRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
    '/_authenticated/travels/$travelId/categories': {
      id: '/_authenticated/travels/$travelId/categories'
      path: '/categories'
      fullPath: '/travels/$travelId/categories'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRouteRoute
    }
  }
}

interface AuthenticatedTravelsTravelIdRouteRouteChildren {
  AuthenticatedTravelsTravelIdCategoriesRoute: typeof AuthenticatedTravelsTravelIdCategoriesRoute
  AuthenticatedTravelsTravelIdEditRoute: typeof AuthenticatedTravelsTravelIdEditRoute
  AuthenticatedTravelsTravelIdExpensesRoute: typeof AuthenticatedTravelsTravelIdExpensesRoute
  AuthenticatedTravelsTravelIdIndexRoute: typeof AuthenticatedTravelsTravelIdIndexRoute
}

const AuthenticatedTravelsTravelIdRouteRouteChildren: AuthenticatedTravelsTravelIdRouteRouteChildren =
  {
    AuthenticatedTravelsTravelIdCategoriesRoute:
      AuthenticatedTravelsTravelIdCategoriesRoute,
    AuthenticatedTravelsTravelIdEditRoute:
      AuthenticatedTravelsTravelIdEditRoute,
    AuthenticatedTravelsTravelIdExpensesRoute:
      AuthenticatedTravelsTravelIdExpensesRoute,
    AuthenticatedTravelsTravelIdIndexRoute:
      AuthenticatedTravelsTravelIdIndexRoute,
  }

const AuthenticatedTravelsTravelIdRouteRouteWithChildren =
  AuthenticatedTravelsTravelIdRouteRoute._addFileChildren(
    AuthenticatedTravelsTravelIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTravelsTravelIdRouteRoute: typeof AuthenticatedTravelsTravelIdRouteRouteWithChildren
  AuthenticatedTravelsNewRoute: typeof AuthenticatedTravelsNewRoute
  AuthenticatedTravelsIndexRoute: typeof AuthenticatedTravelsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTravelsTravelIdRouteRoute:
    AuthenticatedTravelsTravelIdRouteRouteWithChildren,
  AuthenticatedTravelsNewRoute: AuthenticatedTravelsNewRoute,
  AuthenticatedTravelsIndexRoute: AuthenticatedTravelsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
