export const TRAVEL_REPOSITORY = Symbol('TRAVEL_REPOSITORY');
export const EXPENSE_REPOSITORY = Symbol('EXPENSE_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const MEMBER_REPOSITORY = Symbol('MEMBER_REPOSITORY');
export const DASHBOARD_REPOSITORY = Symbol('DASHBOARD_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AUTH_REPOSITORY = Symbol('AUTH_REPOSITORY');
